/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    PostListItem: typeof import('./src/components/PostListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VCreatePost: typeof import('./src/components/VCreatePost.vue')['default']
    VPostList: typeof import('./src/components/VPostList.vue')['default']
    VPostListItem: typeof import('./src/components/VPostListItem.vue')['default']
  }
}
